version: 2

updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  # Frontend npm
  - package-ecosystem: "npm"
    directory: "/blog-api-frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  # Docker images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "docker"
    directory: "/blog-api-frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  # Docker Compose
  - package-ecosystem: "docker-compose"
    directory: "/infra"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
