version: 2

updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3

  # Frontend npm
  - package-ecosystem: "npm"
    directory: "/blog-api-frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3

  # Docker images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3

  - package-ecosystem: "docker"
    directory: "/blog-api-frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3

  # Docker Compose
  - package-ecosystem: "docker-compose"
    directory: "/infra"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
