services:
  app:
    build: .
    container_name: go_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app # 開発用にコードを同期させる
    command: ["go", "run", "main.go"] #開発用にgo runを一時的に使用する  

  frontend:
    build: 
      context: ./blog-api-frontend
      dockerfile: Dockerfile
    container_name: blog_frontend
    ports:
      - "3000:80"
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  test-db:
    image: postgres:15
    container_name: postgres_test
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_TEST_NAME}
    ports:
      - "5433:5432"
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
